apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  labels:
    app: cnkt-event-listener
  name: cnkt-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: TriggerBinding
      ref: cnkt-trigger-binding
    interceptors:
    - cel:
        filter: header.match('X-GitHub-Event', 'push') && body.ref == 'refs/heads/qm1-prod-jsg-guide' && body.repository.full_name == 'prod-jsg-guide/mq-infra-1'
    name: mq-infra-dev
    template:
      ref: mq-infra-dev
  # - bindings:
  #   - kind: TriggerBinding
  #     ref: cnkt-trigger-binding
  #   interceptors:
  #   - cel:
  #       filter: header.match('X-GitHub-Event', 'push') && body.ref == 'refs/heads/master' && body.repository.full_name == 'prod-jsg-guide/mq-spring-app'
  #   name: mq-spring-app-dev
  #   template:
  #     name: mq-spring-app-dev
