apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgB6ealq3+ICam7JB6r7fZ9YkTDICwQsUd6PGRzVsujAqmq9rtoBn/eh2KQ7wkJmn3R1MPY83Uq7Q32n5bIiIT4bNuK08lJShqIodmIeQyPfUGlhOakmiSQoS4+mfn7sSdr9IFdmchpP0Jx1iHloVDxLeDlHSQ/NekRo/Hc992Eb2Ft5I2fL35r6tJickGTB9FbV1HEIpEE1J3mZ2eZ4k1mvG1C0edH0ZOdHLg7cUYEZ0E1q4gGsTG7lq/FhGXa9qP9G5ji3gelRaDGFBaOPvm7E9S92gxsSSz3iH9NfBcZp0TgsuUsWMjIDQjyQI+H8eNzYCWyTNMU3NQhznmv7oDHkR95FGPT7er+F4hFf2azzvMtS+tx/ITxND599Zbfbf8lVXcPNcpUjjoI+i5RaYT29z4XGPfOV08IPbnd0fe41zYuZZzv9lH1nTOUAvekITlQgqcWmGOjhAGT9ugeiXFdf13TVKmdL74Mmwrh8KfHU/oSSY4eq/v6PKh5narIUbPyUuAKSfl79fd9H8iUd2TM3UKiNs2qgsZpwK6c7CNI5pWKxqd0vEFDmEUx0+xH77rs8jE8Iuac8s2raI67wYw88wPxRarjdefB7HBAkKgi5Rqf7kqLWpVKUL/7cG7ex/7DBkv+zwh5mu9AsJP2VMX2tiK72CNrKZrbCW1olAeF8fNjVwQ7BoILj+jlMOQkDEoLdIc2lIqVM+NpaA3uxIGfE4WME/SPGw+ZCxlIGPHUC0vRtulaAkv6F
    username: AgApemSQXAnpoYXcF3Ty2FdHXkkF2jper737BC+AyCdZghOoyo79xdDAJTc0AOcWSmsiwYSV+Y9rwZQoz57P0q4DgYQ6MN3cCk+Umi0VujnPZOO1Eil2Q1G4ZVNJxJ4OdlhS0w8Ry37v4xjfaBqIPS+H6yO24LfZdau6vKYJqdqvFaN4GtKuia+XbJGNyZhFDs1pr2fiqeUpNR2pxu4PK08g187so5AxdL1iXHIwCS/MWj5P+/6GUnMOa1l5eK6S8OyTuos/74VVmsWd1VF8RrtJZ+8zc53SVOzEnDFN01SCSI+liX/1BgVv50j8z3fZpazboXEwekxKgzRunT3bshNhtCjsSbXGbqA5O7FG8+xSOBmPZZt/BOULv0zOMbSEypUO8B8yJJ/rtO1IL4a0ZMysl6GsJFpiaBVlu/tHdy4KXVNff6KGt7ucyjTfIV0UHhrrAZ17xN37+bfU+2oT0BtSorS7yW9k4dnJtCqltPNF8c8sUmctakwIZvC9EUcQSq1+XqA1YDaPyyH5zEcCE1S2MrR+ESPR/tzY4tnMM1Bibh1z/8r0ZgGJJZV5XljG4P8lAQyFngNi6JKfycsYgdqyRP8ssiOv0kbtPdEr6VV8VlZeroojk2dJMprh8byxBhgg04S+dBJHACauBLNUsHvzDP/NeXlZSK9oAHBxi9xyxsal/SsQn8dGTNA2qsH4EGex7IrUgp7AF+++SPzP
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

