apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgAXU4pIJGYP6O7eIsBHxOVkgS0pq077+sTTJ9aZ89U1YOOljLstyTMGjrzTU935Cvvr8PH3a088lTT8esV5tjI8ozM6Qf3urDRcju1D6qHe/ek+Qbe+brpfFieFEFp9VSaAJ6rcYuBxjwXMLg0XuUQ8oiGIPH2c+l5VS+aac3DSByBorw0EjxA8wvUiz87Bf4xd4smJOLzZ2olfHyvxwc1b5kXSRZBqnSliUmzH794IfHu3vJQkGMu0No3Pi2FYxck2wXl5VpMWVj5AYwT1bW/t4dMbdi2m/ElULw9ULTpVVeKVZmMUKlGSXMvW0PTwu5ye4HjrEgeYBUUvArlW0OzuBEpKYmF1qIUHalNjqcZsFHF8BuvVROlQwWcUtXTyeSoxmZfgwU/vzgyYEl4QJ4aVLireRcanrEgPtxjBOJJlmX9cwxDN1EdOAOaTsU2cEcCuIkDri6bbtZLK81Lkg0JbEV5KsqxLogbBX0bHomRHSoKu8HdfQgpe+GPCSovFXt9oul3P2WECc89cI53xcHbi5CKhqpAFp5eZj8Rl/f9OnciipwD6Kax/s3EPITYyRJass4q1OssnqSITDps7gbWBx2XVbDPQzSF1IsQY8trclKU84q2g0S3YK0fhAAWjRwzrr2OnvQSKYwqh6awmA1W5ARzBialBbvelHTnZSyvHPOWL2lU09t998n9p4zWYDGweIXOv0xHeFPhaTqOCOIAHG1uJmM299lKwt9UuEbvsz4+1DzUu8aD7
    username: AgCP3uZXUF/8vZ5oL24/LU4v9Uve7EOFtxltpeKnhFVs49E74Mnw+rIdSi7L761la9qU2s+Ydn56FGzVEXetgUuV8Qhe0+fjWmMRxP9oSsi7d2Aj8WzsLi/JutnkLyMkNiXY8HDauJ/V+YlqsrsUAs3e2pLxWRN7mMLs3Qjjam8DCum9/pQXzoekm+uzzObz045RP9r2rHZpTwtMT31L8RwL29sZLJAfEW/NXwJQdwZlKnGX4+JVs/uZqjuA01aF5HmhEpOAJcxdLHkqHrwQ8MUPJh3KzwOijTMKNW08q7yblSfn994T5ibfhf7X2AAZnSr7UU46KplAEbZRA6Me+BocJpMjSQAblApv8S//Lwbea6wTxKy6sZwpmfUe+o0FVw5p2K/4d8rzodEVIzU3EftWb54yjWKFAMiUl0OD3fXOv+6k/KdWkdqMsNMDoez88tPh6wjvDatTHkewIwvoicWwKN+75TOxN3uDDlMprNinJAc9EvLahrSr9ml/IJIYVrtK79Q/Ovno8BlfVnQMwOfyPGPZOjCXcXx3wYxdPW9g7PfiRXQR8aEkrp0wz1a6bHV3TsONPVw45Fzef4LSEUmuMfxpxtG0ZSeIKWSmdBFDI/Pt/KXiRbONSdBYFTtXYsLJPN9HFZfVoKPMS69FVW7Qc1mJRwNmIpEGGuPiBP513c0QcbGjZTCP9ALT8MFFyyyJPR3p8GAbT2QBVOJ8
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

