apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgB2adRgijn3EQzUc3f3XX5nDgh+2PvgqhZbhRPy+RL+ipELzXBX87u/wACXqh6dcKz2OLtc0lQ5Gp1pmoPt/Ju607/w1FKVBtKN63NMNkX0RRrVjlvtdGKS9xe4L6QEqUGyAd0GYK2j4yCaMpIlWr3f94P0MFUkFuW9PJl/urXKkkkSINo0dSM8D1m1WNg6LdXQ8aNn3rwE5olPOtainRaBe++an0zZEev32poPoTBL6v9jZYW+1E++dn8RdfVtyhe4Kkc3W1Eui6cabwmHpFPXf5PYqNiqHUl8AMCr+rXrDLIXkACsdgTQPDj+q8fK5FX6W/+NQC9JnpqgJnCZhPijjQYgPAWVhiyEh/Xc9+GEaNmMRxAdzKeU32vzigFymKXWV3cOhwfoYh1lzQpcjZcl2nI5t8/BtX1Mc6zT5mICrI7WTWqCEFjJ4fDXJbVYN5opd8ADMMjpfXbq7TMIN3VvSQyvnG+/n6ujetDJQ5TJ8vZqs+FjrM9GX6Ev3sOYgFsjHDDbjZJF+p4d5qAvlKd7zzOnC1f7RXqjtIOclw6fG/iKoDHUoRe+tcpa10IDoCzIrRi0qff6xmYOnVNbfWWFpZPEdrGw+Gbn7D2hTShE0fyu/GdEbcO14vezdIFimqlG5CtERWTybeIBrpDPRZDYYXgnip4cFeXcvhGaE5E7YhfNsi0B8RKOPGP9yq+CAci6c9KmNve6EUyedz9W3LXn2WEAUK2CcD3SOjl2O0jbp/SQSgrH45TW
    username: AgBIp4wQm22W67J+Y2MIoTFiq2GrRbwrOPGIFbycooffST5bchKMEXBwpJ71XJuqnoIyGBdZmm5MIc6Hf+p2BCVuuttruMzwIMm/V/A3wzZ+uOtZnqCCbPTiNRjoLMEK6e8c1wZmryS0HQZmR0qDw3Y9MgQXMBsCOILkq6BR8MYj30FCvB4mWGvPIzYTQ/hHotSVt8d8wPqvtElHEb92NYvBlUPDHJU15UlpjQ+sjPitRncmwDjtOWRbK+shb8fQ6MhdAVK01gBW/W4bL9nZrQyyKR3F7WByjXM/toEsqtbAfTro+VzrFIvcsiZ9HiTQCuasnbWxac5YykuiRKL6aum+uCCccW1xuPxZ+H0hKXOJC6Gqdy0Bi1XIo8JOlcxGziDam0MQLo+lN6NBYpA+/wESbZ8hSQHlD+lj4ZvKIf2NQW+kqjGPK/9cYcaEYGqxpUR9rGdstFubNUyNsjEq5aRdBWmJ6Pr0S7LExBtx58GsSmDT606Imel5UNh8ybk/T5k9I1jI/b/1vH7dfTtJpQ4MBc3C1lob2RpiHW4Emaw725z/3Y60vcqokyaflwddrglANo6k9IYYnzv77CPcmRMo3EvyYJYHiG2yI0d6F36OdGyCrGzuuAtkzSCDtsascZZTXtN/9qEzKg/NuNNkKOdP+5DD9XbMNKF2sM8iUm/FEI6Du4BbOkLBc0Z8ayjhRTR94XSw7XZC01CFbQIW
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

