apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgC0OKLeIl21TcohIPPBP/VewrepPVcPGfQCiWYxFkzzz8y+7Uo735SrF8H2dMyZIAv8C4Dy+I+SizaSL6Omltv6StJK8SosUnj8nlZF3yy2aFNnWs73uDdcbrKAdlfoKR56r+413oPHVWACbOiqt85NCubDOtOkJnc7zUj2ytE4YNSX6uaXl2aXgJ9jhGbsp4o2bdV+WhP0brizrkPC2n5i1vxrERmKuK0CXbh0AgA55ztaV5zG0ToJOBrDm5DlzXz8cBf7wGPwxHWQSLMTtRo74+MeDpA4Lu6Pa3GJsjPV4r8Ve2KP5Xgg7TI7YP7J7Hvz9RbpF2OJKeRNWvIsxLl33dfienHWuDScDhmW25+oISdH7x0rI2ubWeAMJTCNolb1Q2tS37kML6fONhX1GhnOv3lpul7X31yrDcd/7iebIYBfniudnwh8SkLMsRSaFNgMGGTfvY8tGpj3N+rlsynflEL2Z/SBUN7Igo/qYLfkjoKJQ0mOzGq/tPcbxVwNhfP4RZnCaH8/k2fxtJp5AYisFMO449JphZ3FUwtKjXnvBde0HLEstOBe6NrfFeV1UrBde2ZfjYhfUDbtnAWNU8ra4XzTnhXHvD6Jrl/HfqnOOPuqtCCrGQb4NZje4xuHTQXhoPuY4DvesNj7GYLt74Lkgis9Q4jpoZ48frZTOx7B94wo6nG6XqtKtjDnPWLZsUcGx/BlhN+NNofSIt6L0VdnrCJfdn+xcnRcXgl4UZoZyGuhUFedP+fUs5i3ThmJUmgJWtTJhrlo2VfCQoGmU6isK5Kh5d6Zr3dZToFLYPiZjUZDKXlAWK7PjtL0m/yAcygpG9jnfbUpIpaDCoHm8Q9I3J9O3wJuGDUgmYlnV7kjAxIyzS8z2tsoVwYbwn9AM0bV+twTsz5c+2WcLuMaIKM0d8kFmJ1X+LzPmekTBapg/A==
    IBM_ENTITLED_REGISTRY_USER: AgA2ivv1YeUMLLRx54Qjb1teURBtt89ZCb36d6lvzBwHr9jtvY7tNWEcSJZ8wKhgaqZEhPx0YCeqdtLcL5wUvC0HrhU2ED0vc8nGZpMxV/NDOH+w30iOda8GPlw0pV08ttpgrDngFE8EoX0O8tFYvvlnsvNTgsp1wwSoEIAA9GdTG1LRsdJFeojS3UidLV3OmRkV42JLlE9B4lcuKaVvSzpY/Q0ArFhj71AmfY+xen5ACiEmvoLK9zOiTCvizx61PzS9v2acgV1d43RCY3ZNBujxRLTB/W6ZCTg62XGFoyluc7F2+MI9WQYmSyfn7QBSm6cn35pV2a7DNoX9fDVdFgZlr1O211p0Ltr13mzFFbl1zyF05PXCDuqdYnHmjqkjs4TUsUveCUjfFDGBRkddrLg7sjnPqMvyN+zWyOTJCmVp0K/JzN2+18vs92tz21PuEL3jDxBPbbtKCsCMA5EZ8AF3kiXK6RnNokI34r6TS5LYMIwK0oeEtgk92qFlJYKHEc4S8eTVY5QZNrfwLTr0sTy/UitJn7gmzCQ/BjnEvar+tMpi3hyzprUHzbKdC8Yb2AvdDn8r98oWxJU7YME87ZOufboH1CnHpbq6iKzhL/IbaVYXsZ2m7woIev8cuATCKGEOWYMqONW+sC4TLujxB5vxI45pFj2uZGct0vqQKuZUhuna2MMdoRh86lO8ZG6TPaPfeQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

